Repository OpenGeekBrains/HR_in_pocket, pull requests merged in 2020-11, with the labels that each got.

#39 Ui
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/MakeTaskController.cs
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/RegistrationController.cs
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Callback.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Executor.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_GetDreamJob.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_HowWorks.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Price.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Tarifs.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/MakeTask/Index.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Registration/Index.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Partial/_Executor.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Partial/_MainMenu.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/_LayoutMakeTask.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/_LayoutRegistration.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/wwwroot/css/site.css
  src/HRInPocket/UI/WEB/HRInPocket/wwwroot/img/plashka-photo.png
Labels: UI

#51 Расширение для упрощения инициализации таблиц в базе данных
  src/HRInPocket/Services/HRInPocket.DAL/Data/DbContextExtensions.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
Labels: БД

#60 Сборка моделей в Domain
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Base/BaseEntity.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Base/NamedEntity.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/ActivityCategory.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Address.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Company.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/CoverLetter.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/CoverLetterValue.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/PriceItem.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Profile.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Resume.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/ResumeValue.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Speciality.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/TargetTask.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Tarif.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Vacancy.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/Applicant.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/SystemManager.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/User.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entityes/Applicant.cs
  src/HRInPocket/Common/HRInPocket.Domain/Enums.cs
  src/HRInPocket/Common/HRInPocket.Domain/HRInPocket.Domain.csproj
  src/HRInPocket/Services/HRInPocket.Clients/HRInPocket.Clients.csproj
  src/HRInPocket/Services/HRInPocket.DAL/Data/ApplicationDbContext.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/DbContextExtensions.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestDbInitializer.cs
  src/HRInPocket/Services/HRInPocket.DAL/HRInPocket.DAL.csproj
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201114173059_AddPrice.Designer.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201114173059_AddPrice.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201115115801_Create.Designer.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201115115801_Create.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/ApplicationDbContextModelSnapshot.cs
  src/HRInPocket/Services/HRInPocket.DAL/Service/IDisposableExtensions.cs
  src/HRInPocket/Services/HRInPocket.Interfaces/HRInPocket.Interfaces.csproj
  src/HRInPocket/UI/WEB/HRInPocket/Components/PriceItemCardViewComponent.cs
  src/HRInPocket/UI/WEB/HRInPocket/Components/TarifCardViewComponent.cs
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/AccountController.cs
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/HomeController.cs
  src/HRInPocket/UI/WEB/HRInPocket/Startup.cs
  src/HRInPocket/UI/WEB/HRInPocket/ViewModels/Account/UserProfileViewModel.cs
  src/HRInPocket/UI/WEB/HRInPocket/ViewModels/ErrorViewModel.cs
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Price.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Tarifs.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Components/PriceItemCard/Default.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Components/TarifCard/Default.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/_ViewImports.cshtml
Labels: БД

#66 Добавление AutoMapper в проект HRInPocket
  src/HRInPocket/UI/WEB/HRInPocket/HRInPocket.csproj
  src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Profiles/AccountsProfile.cs
  src/HRInPocket/UI/WEB/HRInPocket/Startup.cs
  src/HRInPocket/UI/WEB/HRInPocket/ViewModels/Account/UserProfileViewModel.cs
Labels: Сервисы

#63 Перестройка уровня Domain
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Base/BaseEntity.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Base/NamedEntity.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/ActivityCategory.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Address.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Company.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/CoverLetter.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/CoverLetterValue.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/PriceItem.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Profile.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Resume.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/ResumeValue.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Speciality.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/TargetTask.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Tarif.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Data/Vacancy.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/Applicant.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/SystemManager.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entities/Users/User.cs
  src/HRInPocket/Common/HRInPocket.Domain/Entityes/Applicant.cs
  src/HRInPocket/Common/HRInPocket.Domain/Enums.cs
  src/HRInPocket/Common/HRInPocket.Domain/HRInPocket.Domain.csproj
  src/HRInPocket/Services/HRInPocket.Clients/HRInPocket.Clients.csproj
  src/HRInPocket/Services/HRInPocket.DAL/Data/ApplicationDbContext.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/DbContextExtensions.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestDbInitializer.cs
  src/HRInPocket/Services/HRInPocket.DAL/HRInPocket.DAL.csproj
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201114173059_AddPrice.Designer.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201114173059_AddPrice.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201115115801_Create.Designer.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201115115801_Create.cs
  src/HRInPocket/Services/HRInPocket.DAL/Migrations/ApplicationDbContextModelSnapshot.cs
  src/HRInPocket/Services/HRInPocket.DAL/Service/IDisposableExtensions.cs
  src/HRInPocket/Services/HRInPocket.Interfaces/HRInPocket.Interfaces.csproj
  src/HRInPocket/UI/WEB/HRInPocket/Components/PriceItemCardViewComponent.cs
  src/HRInPocket/UI/WEB/HRInPocket/Components/TarifCardViewComponent.cs
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/AccountController.cs
  src/HRInPocket/UI/WEB/HRInPocket/Controllers/HomeController.cs
  src/HRInPocket/UI/WEB/HRInPocket/HRInPocket.csproj
  src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Profiles/AccountsProfile.cs
  src/HRInPocket/UI/WEB/HRInPocket/Startup.cs
  src/HRInPocket/UI/WEB/HRInPocket/ViewModels/Account/UserProfileViewModel.cs
  src/HRInPocket/UI/WEB/HRInPocket/ViewModels/ErrorViewModel.cs
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Price.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Home/Partial/_Tarifs.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Components/PriceItemCard/Default.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/Shared/Components/TarifCard/Default.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/Views/_ViewImports.cshtml
Labels: БД

#65 Корректирование страницы создания задания
  src/HRInPocket/UI/WEB/HRInPocket/Views/MakeTask/Index.cshtml
  src/HRInPocket/UI/WEB/HRInPocket/wwwroot/css/site.css
Labels: UI

#62 Подключение десктопного приложения к парсеру.
  src/HRInPocket/HRInPocket.sln
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru.csproj
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Interfaces/IParsehh.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Base/BaseUnit.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Company.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Metadata.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Vacancy.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/VacancyName.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
  src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/AngleSharp-Console-Test.csproj
  src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/App.xaml
  src/HRInPocket/UI/WPF/HRInPocket.WPF/App.xaml.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/HRInPocket.WPF.csproj
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Infrastructure/Commands/Core/CommandCore.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Infrastructure/Commands/LambdaCommand.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/MainWindow.xaml
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Program.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Services/Interfaces/ISaveDataToJSON.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Services/SaveDataToJSON.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/ViewModels/Core/ViewModelCore.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/ViewModels/Core/ViewModelLocator.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/ViewModels/MainWindowViewModel.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Views/MainWindow.xaml
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Views/MainWindow.xaml.cs
Labels: UI

#69 Parser refactoring
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru.csproj
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Interfaces/IParsehh.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Interfaces/IParsehhService.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Base/BaseUnit.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Company.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Company.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Metadata.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/Vacancy.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Entites/VacancyName.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Metadata.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Vacancy.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParseHHVacancyException.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
  src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/VacancyEventArgs.cs
  src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/AngleSharp-Console-Test.csproj
  src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Data/TestData.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/HRInPocket.WPF.csproj
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Services/SaveDataToJSON.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/ViewModels/MainWindowViewModel.cs
  src/HRInPocket/UI/WPF/HRInPocket.WPF/Views/MainWindow.xaml
Labels: UI

#77 Logger
  .gitignore
  src/HRInPocket/Services/HRInPocket.DAL/Data/TestDbInitializer.cs
  src/HRInPocket/Services/HRInPocket.Services/Services/CompanyService.cs
  src/HRInPocket/UI/WEB/HRInPocket/HRInPocket.csproj
  src/HRInPocket/UI/WEB/HRInPocket/Program.cs
  src/HRInPocket/UI/WEB/HRInPocket/Startup.cs
  src/HRInPocket/UI/WEB/HRInPocket/appsettings.Development.json
  src/HRInPocket/UI/WEB/HRInPocket/appsettings.json
Labels: Сервисы
